name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - "index.html"



jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
